### ISSUE TITLE
Auto Updater

### ISSUE THREAD

**Issue by 0x783czar** [DarkDefender/weetweet#18] opened 2017-12-14 23:21 UTC
The doc string for the :new_tweets command refers to the "Auto Updater", what is this and how do I enable it?  I'd like to no have to keep running that command to see the latest tweets.

**Comment by DarkDefender** [comment] 2017-12-15 06:44
Ah, that is an old relic that survived the stream rewrite. There is no "auto updater". Now we have streaming instead. So if weetweet doesn't mention anything about failing to start the stream, you do not have to do anything.

**Comment by 0x783czar** [comment] 2017-12-15 19:01
Hmm, however I'm not seeing new updates come in unless I manually run the :new_tweets command.  And I definitely haven't seen any errors about not being able to start the stream.  Anywhere I should check?

**Comment by DarkDefender** [comment] 2017-12-15 22:37
It should tell you when you start the script if it fails to start the twitter stream. It will print error messages either in the twitter buffer of the weechat root buffer

**Comment by DarkDefender** [comment] 2018-01-01 14:08
I'm closing this as there isn't really any info provided here that can help me understand what the issue is.

**Closed by DarkDefender** 2018-01-01 14:08 UTC

**Comment by StarlitGhost** [comment] 2018-08-06 10:48
I'm having the same issue, no updates unless I ask for them, and no errors on script load in either the twitter buffer or the weechat root buffer.
I'm going to sprinkle some debug prints in the script and see if I can find anything.

**Comment by DarkDefender** [comment] 2018-08-06 10:58
Are you using the script from this repo? The one in the weechat script repo is using deprecated twitter APIs that should have been removed now. I will try to updated the script in that repo now.

**Comment by DarkDefender** [comment] 2018-08-06 16:08
Ok, then I do not know what could be the cause. Try to add some debug output as you said and report back if you find anything

**Comment by StarlitGhost** [comment] 2018-08-09 15:14
A few days and a weechat upgrade later, and this issue has mysteriously fixed itself.

I'm on the dev version of weechat, so there were no major changes to explain this. Oh well!

**Comment by DarkDefender** [comment] 2018-08-10 07:11
What version were you on previously? I'm not on the dev version and it works.

Anyways, thanks for the report! :)
