### ISSUE TITLE
Compatibility with python-twitter 1.18?

### ISSUE THREAD

**Issue by nilsdeppe** [DarkDefender/weetweet#19] opened 2018-01-17 02:05 UTC
Hi,

Thanks for the cool plugin! Unfortunately I'm having some trouble with getting it to work on my machine. I've installed the python-twitter library, but the ` from twitter.stream import Timeout, HeartbeatTimeout, Hangup` call fails. Unfortunately I don't know anything about python-twitter and so cannot help. Any advice would be appreciated!

**Comment by DarkDefender** [comment] 2018-01-17 06:49
I haven't tried 1.18 yet. I guess there is some API breakage going on. I'll take a look at it soonish.
If you installed the lib via `pip` you could just tell it to install an other version of the twitter library instead:
`pip install -Iv twitter==1.7.1`

**Comment by DarkDefender** [comment] 2018-01-19 07:08
I have tried 1.18.0 and I do not seem to have any issues with it sadly. I can not reproduce this problem. So I need your help to solve this.

**Comment by slackhead** [comment] 2018-02-15 01:11
The only way I got 1.18.0 to work was to build the package for both python 2 and 3. Python3 last.

I guess some files got overwitten somehwere, but it loads. The only issus I'm having is that the new 280 char tweets are getting cut at less than that, but I guess that's an issue with the twitter lib somewhere.

**Comment by DarkDefender** [comment] 2018-02-15 06:52
Yes, that is an issue with the twitter lib. But it seems like it can be solved now:
https://github.com/sixohsix/twitter/issues/377

So I guess I'll look into it soon.

**Comment by slackhead** [comment] 2018-02-15 06:58
I have managed to edit weetweet.py to print the full tweets, but I'm still testing it. I had some problems with my own tweets, but I think that is also fixed now.

When I've tested it a little longer I'll send a PR.

**Comment by DarkDefender** [comment] 2018-02-15 15:58
Ok, I'll wait for your pull request then! :)

**Comment by DarkDefender** [comment] 2018-02-23 19:30
@slackhead how's that testing going? ;)

**Comment by slackhead** [comment] 2018-02-23 19:36
Well, I have it all working apart from the home userstream, which looks like it lacks full_text/extended support.

I asked on the twitter dev forum about it and was told that they were going to drop user streams soon and it'd be better to use the api.twitter.com instead. I think that this would mean settings up a timer and polling your home stream every so often. That would take me some time to look into. My python is pretty basic at the moment.

**Comment by DarkDefender** [comment] 2018-02-24 12:08
I've looked at it a bit now and I have to say that it sadly seems like Twitter has not backed down on serverly gimping 3rd party apps over the years.

Right when I started writing this plugin, you could get the same functionallity (easily) as the official twitter app. However over the years they removed many useful features (like getting the reply chain for other tweets then yours) and upping the rate limit on requestes slowly over time (making it impossible for to do things fancy things withing risking getting your app/client banned) and now finally they are taking away the ability to get updates to your home timeline in realtime.

It is obvious to me that the api in now geared towards bots and website interfaces, not end users applications...

Funny enough the new suggested way to quiery home timeline tweets were the way I originaly did it. However it resulted in cases where you could easily get yourself suspended if you refreshed to fast.

Don't get me wrong I will try to update the plugin to not use userstreams anymore. But I don't like where this is going.

@slackhead could you create a pull request of your current work so I could build on it?

**Comment by DarkDefender** [comment] 2018-10-12 14:59
I think this issue is solved now.

**Closed by DarkDefender** 2018-10-12 14:59 UTC
